/*Built-in Exception class....
 Arithmatic Exception with try and finally
 */
class Demo
{
  public static void main(String arg[])
  {
    int b=0,c=0,d=0,e=0;
    try
    {
      int a=10;
        b=a+5;
        c=a-3;
        d=a/0;
        e=a*4;
    }
    finally
    {
      System.out.println("Addition="+b);
      System.out.println("Substraction="+c);
      System.out.println("Division="+d);
      System.out.println("Multiplication="+e);
    }
  }
}
/*
Output:-
bcs@PRATHAMA:~$ javac Arithmatic_Exception4.java
bcs@PRATHAMA:~$ java Demo
Addition=15
Substraction=7
Division=0
Multiplication=0
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at Demo.main(Arithmatic_Exception4.java:14)
*/
