/*Built-in Exception class....
 NegativeArraySize Exception with try and catch
*/

class Demo
{
 public static void main(String arg[])
   {
     try
       {
         int a[]=new int [-5];
         System.out.println("Array Create Successfully");
         a[0]=10;
         a[1]=20;
         a[2]=30;
	System.out.println("Value Insert Successfully");
	System.out.println("Value Display="+a[1]);
       }
     catch(Exception e)
       {
         System.out.println("Error="+e);
         
       }
   }
}

/*
Output:-
bcs@PRATHAMA:~$ javac NegativeArray_Exception.java
bcs@PRATHAMA:~$ java Demo
Error=java.lang.NegativeArraySizeException: -5
*/
